version: '3.8'

services:
  payment-service:
    build:
      context: ./ServicePayment
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8081:8080"
    networks:
      - springboot-network

  user-service:
    build:
      context: ./ServiceUser
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8080"
    networks:
      - springboot-network

  order-service:
    build:
      context: ./ServicesOrder
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:8080"
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
