version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: jenkin
        MYSQL_ROOT_PASSWORD: vinay
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
       - springboot-network
  payment-service:
    build:
      context: ./ServicePayment
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8081:8080"
    networks:
      - springboot-network

  user-service:
    build:
      context: ./ServiceUser
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - springboot-network

  order-service:
    build:
      context: ./ServicesOrder
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:8080"
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge