pipeline {
    agent any

    environment {
        SERVICE_NAME = "ServiceOrder"
        JAR_NAME = "ServiceOrder-0.0.1-SNAPSHOT.jar"
        DOCKER_IMAGE = "vinay020/service-order"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                dir("${env.SERVICE_NAME}") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${env.SERVICE_NAME}") {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials-id') {
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Deploy (optional for local)') {
            steps {
                sh 'docker-compose down'
                sh 'docker-compose up -d --build'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
    }
}
